services:
  mi-servidor:
    build: .
    ports:
      - "3000:3000"
    networks:
      red-segura:
        ipv4_address: 172.20.0.2

  proxy-socks:
    image: serjs/go-socks5-proxy
    environment:
      - REQUIRE_AUTH=false  # <--- Esto evita el error de autenticación
    networks:
      red-segura:
        ipv4_address: 172.20.0.10

  atacante:
    image: node:18-slim
    tty: true
    stdin_open: true
    volumes:
      - .:/app        
    working_dir: /app  
    networks:
      red-segura:
        ipv4_address: 172.20.0.5

networks:
  red-segura:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24